### ISSUE TITLE
unpack requires a string argument of length 8

### ISSUE THREAD

**Issue by easthg** [deepinstinct/dsc_fix#1]
System:  macOS 10.12
Some error occur  when open dyld_shared_cache_arm64.

/Users/XiaoMi/Desktop/dsc_fix.py: unpack requires a string argument of length 8
Traceback (most recent call last):
  File "/Applications/IDA Pro 6.95/idaq64.app/Contents/MacOS/python/ida_idaapi.py", line 509, in IDAPython_ExecScript
    execfile(script, g)
  File "/Users/XiaoMi/Desktop/dsc_fix.py", line 760, in <module>
    main()
  File "/Users/XiaoMi/Desktop/dsc_fix.py", line 744, in main
    adrfind = AddrFinder(dsc_file, cache_symbols=False)
  File "/Users/XiaoMi/Desktop/dsc_fix.py", line 402, in __init__
    self.indexer.index()
  File "/Users/XiaoMi/Desktop/dsc_fix.py", line 377, in index
    self.dyldwalker.walk_segments(self._callback, verbose=verbose)
  File "/Users/XiaoMi/Desktop/dsc_fix.py", line 329, in walk_segments
    verbose=verbose)
  File "/Users/XiaoMi/Desktop/dsc_fix.py", line 338, in walk_images
    mappings = dyld_cache_mapping_info(self.cache, header.mapping_count)
  File "/Users/XiaoMi/Desktop/dsc_fix.py", line 174, in dyld_cache_mapping_info
    ret.append(_dyld_cache_mapping_info(dsc_file))
  File "/Us

**Comment by daniel-bluesea** [comment]
@easthg did you manage to solve it? it happened to me as well

**Comment by daniel-bluesea** [comment]
open ida, without a target file, then run python script, the script will open a file dialog, then choose your target file.
the error you mentioned wont appear.

having said that, the script itself failed to affect my target file, and also caused ida to crash several times..
but thats a different issue :)
